version: '3'
services:
  oacis:
    image: oacis/oacis:${OACIS_IMAGE_TAG:-latest}
    volumes:
      - ./Result:/home/oacis/oacis/public/Result_development
    environment:
      - LOCAL_UID
      - LOCAL_GID
      - LOCAL_USER
    ports:
      - "${HOST_IP:-127.0.0.1}:${OACIS_PORT:-3000}:3000"
    tty: true
    extra_hosts:
      - "gateway.docker.internal:host-gateway"
